"Resources"
{
	"materials/hud/leaderboard_class_demo_clusterbomb.vmt"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_warriorsspirit.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_warriorsspirit.vtf"	"file"
	"materials/hud/leaderboard_class_medic_blast.vmt"	"file"
	"materials/hud/leaderboard_class_medic_blast.vtf"	"file"
	"materials/hud/leaderboard_class_medic_blast_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vmt"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vtf"	"file"
	"materials/hud/leaderboard_class_medic_bullet_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_crossbow.vmt"	"file"
	"materials/hud/leaderboard_class_medic_crossbow.vtf"	"file"
	"materials/hud/leaderboard_class_medic_crossbow_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vmt"	"file"
	"materials/hud/leaderboard_class_medic_kritz.vtf"	"file"
	"materials/hud/leaderboard_class_medic_kritz_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vtf"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_uber_giant.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_heal.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_heal.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_neonsign.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_neonsign.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_bison.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_bison.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_bison_giant.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_disciplinary.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_disciplinary.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_dumpster.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_dumpster.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_rocketrain.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_rocketrain.vtf"	"file
}

