"Resources"
{
	"materials/hud/leaderboard_class_demoknight_samurai_sakura.vmt"	"file"
	"materials/hud/leaderboard_class_demoknight_samurai_sakura.vtf"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb.vmt"	"file"
	"materials/hud/leaderboard_class_demo_clusterbomb.vtf"	"file"
	"materials/hud/leaderboard_class_heavy_grapple.vmt"	"file"
	"materials/hud/leaderboard_class_heavy_grapple.vtf"	"file"
	"materials/hud/leaderboard_class_medic_blast.vmt"	"file"
	"materials/hud/leaderboard_class_medic_blast.vtf"	"file"
	"materials/hud/leaderboard_class_medic_blast_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vmt"	"file"
	"materials/hud/leaderboard_class_medic_bullet.vtf"	"file"
	"materials/hud/leaderboard_class_medic_bullet_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_crossbow.vmt"	"file"
	"materials/hud/leaderboard_class_medic_crossbow.vtf"	"file"
	"materials/hud/leaderboard_class_medic_crossbow_giant.vmt"	"file"	"file"
	"materials/hud/leaderboard_class_medic_fire.vmt"	"file"
	"materials/hud/leaderboard_class_medic_fire.vtf"	"file"
	"materials/hud/leaderboard_class_medic_fire_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_needle.vmt"	"file"
	"materials/hud/leaderboard_class_medic_needle.vtf"	"file"
	"materials/hud/leaderboard_class_medic_needle_giant.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vmt"	"file"
	"materials/hud/leaderboard_class_medic_shield_qf.vtf"	"file"
	"materials/hud/leaderboard_class_medic_syringe.vmt"	"file"
	"materials/hud/leaderboard_class_medic_syringe."vtf"	"file"
	"materials/hud/leaderboard_class_pyro_airblast.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_airblast.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_heal.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_heal.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_neon.vmt"	"file"
	"materials/hud/leaderboard_class_pyro_neon.vtf"	"file"
	"materials/hud/leaderboard_class_pyro_neon_giant.vmt"	"file"
	"materials/hud/leaderboard_class_scout_cleaver_2.vmt"	"file"
	"materials/hud/leaderboard_class_scout_cleaver_2.vtf"	"file"
	"materials/hud/leaderboard_class_scout_fanowar.vmt"	"file"
	"materials/hud/leaderboard_class_scout_fanowar.vtf"	"file"
	"materials/hud/leaderboard_class_scout_lime.vmt"	"file"
	"materials/hud/leaderboard_class_scout_lime.vtf"	"file"
	"materials/hud/leaderboard_class_scout_milk_2.vmt"	"file"
	"materials/hud/leaderboard_class_scout_milk_2.vtf"	"file"
	"materials/hud/leaderboard_class_sniper_huntsman_bleed.vmt"	"file"
	"materials/hud/leaderboard_class_sniper_huntsman_bleed.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_dumpster.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_dumpster.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_risingsun.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_risingsun.vtf"	"file"
	"materials/hud/leaderboard_class_soldier_sakura.vmt"	"file"
	"materials/hud/leaderboard_class_soldier_sakura.vtf"	"file"
}

